### ISSUE TITLE
websocket: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by chapolito** [chapolito/gotrader#2]
need to restart websocket connection if it errors/timesout? not sure what is happening here exactly.

**Comment by chapolito** [comment]
systemd does not restart when this happens.

**Comment by ARolek** [comment]
since the program is not crashing systemd wont know to respawn it. If you want to crash the program so systemd would respawn it, you can change the `println(err.Error())` [here](https://github.com/chapolito/gotrader/blob/789f712baaa432fb29d540e09a792e1d5ee2a9b1/MonitorExchange.go#L31) to a `panic(errr)`. 

I don't usually suggest this as it's better to handle the disconnect and work to reestablish the connection. That approach does however open up numerous other questions (i.e. what if a buy order was trying to be sent, should we hold the buy order, re-connect, and try to resubmit it? What if the buy order is no longer valid, do we need to re-evaluate it? Maybe after a certain period of not being able to re-connect we consider the buy order stale? etc. etc.). 

This considered, just crash the program for now and have it start back up. Not a great solution, but it is "pure" in the sense that you don't have a lot of strange considerations to think through. The only real downside in this situation is you may miss a buying opportunity during the crash / reboot cycle.

**Comment by chapolito** [comment]
Thanks, this makes a ton of sense. I ended up changing a coupe days ago the systemd line `Restart=on-failure` to `Restart=always` and that 'fixed' it in the manner that you described. This works for me, and I'm not _too_ worried about missing a buy opportunity. 

Going to mark this as fixed as I don't plan to handle the reconnect gracefully...too complicated :) 

Thanks dude!
